local cbuf = require "ll-cbuf"
local b = cbuf.buf("abc")
local bl = cbuf.bufs()
print(package.path)
print(package.cpath)
print('type(b)', type(b))
print('type(bl)', type(bl))
cbuf.append(bl, b)
cbuf.append(bl, b)
cbuf.append(bl, b)
print("#b", #b)
print("#bl", #bl)
print("b.tostring", cbuf.tostring(b))
